version: '3'

services:
  goravel:
    container_name: page_builder
    build:
      context: .
    image: ghcr.io/abdabariassalam/belajar-web-goravel:latest
    ports:
      - "3000:3000"
    volumes:
      - ./public:/www/public
      - ./storage:/www/storage
    restart: always
    networks:
      - belajar_web

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: page_builder
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - belajar_web

networks:
  belajar_web:
    driver: bridge

volumes:
  postgres:
  mysql: