version: '3'

services:
  goravel:
    container_name: page_builder
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    networks:
      - belajar_web

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: page_builder
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - belajar_web

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'page_builder'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql

networks:
  belajar_web:
    driver: bridge

volumes:
  postgres:
  mysql: